class_name TiangZClient
extends Node

## Godot WebSocket SDK适配；连接流程手写，协议Codec由主工程自动生成。
## Godot WebSocket SDK adapter; flow is handwritten, while protocol codecs are generated by the main project.

signal status_changed(text: String, is_error: bool)
signal map_entered(snapshot: Dictionary)
signal map_ready(snapshot: Dictionary)
signal navigate_push(message: Dictionary)
signal aoi_delta(message: Dictionary)
signal entity_enter(entity: Dictionary)
signal entity_leave(unit_id: int)
signal entity_numeric(message: Dictionary)
signal entity_state(message: Dictionary)
signal door_changed(closed: bool, changed: bool)
signal ping_result(latency_ms: int, server_time_ms: int)
signal auto_attack_state_changed(state: Dictionary)
signal item_changed(item: Dictionary)
signal buff_added(buff: Dictionary)
signal buff_removed(message: Dictionary)
signal buff_detail(message: Dictionary)
signal quest_progress(message: Dictionary)
signal skill_cast_state(message: Dictionary)
signal skill_projectile(message: Dictionary)
signal skill_impact(message: Dictionary)
signal loot_inspected(message: Dictionary)
signal loot_result(message: Dictionary)
signal session_replaced(message: Dictionary)

var peer: WebSocketPeer
var account: String
var password: String
var auth_mode := "login"
var phase := "idle"
var next_rpc_id := 1
var pending: Dictionary = {}
var connect_callback: Callable
var socket_opened := false
var last_ping_ms := 0
var ping_sent_at := 0
var token := ""
var door_request_pending := false
var auto_attack_request_pending := false
var item_request_pending := false
var skill_request_pending := false
var quest_request_pending := false
var loot_inspect_request_pending := false
var loot_request_pending := false

## 开始登录流程；这里只保存本次连接所需的凭据，不落盘也不打印密码。
## Starts login flow; credentials stay in memory for this connection and are never persisted or logged.
func start(in_account: String, in_password: String, login_mgr_host := "127.0.0.1", login_mgr_port := 7000) -> void:
	account = in_account
	password = in_password
	auth_mode = "login"
	_emit_status("正在连接 LoginMgr %s:%d" % [login_mgr_host, login_mgr_port], false)
	_connect(login_mgr_host, login_mgr_port, Callable(self, "_request_login_service_addr"))

## 注册成功后继续复用同一条Login连接登录，保持Godot与Cocos3D相同的用户体验。
## After registration, reuse the Login connection and continue into login for the same UX as Cocos3D.
func register(in_account: String, in_password: String, login_mgr_host := "127.0.0.1", login_mgr_port := 7000) -> void:
	account = in_account
	password = in_password
	auth_mode = "register"
	_emit_status("正在连接 LoginMgr %s:%d" % [login_mgr_host, login_mgr_port], false)
	_connect(login_mgr_host, login_mgr_port, Callable(self, "_request_login_service_addr"))

func _process(_delta: float) -> void:
	if peer == null:
		return
	peer.poll()
	var state := peer.get_ready_state()
	if state == WebSocketPeer.STATE_OPEN and not socket_opened:
		socket_opened = true
		if connect_callback.is_valid():
			var callback := connect_callback
			connect_callback = Callable()
			callback.call()
	elif state == WebSocketPeer.STATE_CLOSED:
		if phase != "closed":
			_emit_status("WebSocket已关闭", true)
			phase = "closed"
			peer = null
			pending.clear()

	while peer != null and peer.get_available_packet_count() > 0:
		_handle_packet(peer.get_packet())

	if phase == "map" and Time.get_ticks_msec() - last_ping_ms >= 5000 and not _has_pending_response(TiangZProto.G2C_PING):
		last_ping_ms = Time.get_ticks_msec()
		ping_sent_at = last_ping_ms
		_send_rpc(TiangZProto.C2G_PING, TiangZProto.encode_c2g_ping({}), TiangZProto.G2C_PING, Callable(self, "_on_ping"))

func navigate_to(x: float, y: float, z: float, sequence: int) -> bool:
	if phase != "map":
		return false
	_send_rpc(TiangZProto.C2M_NAVIGATE_TO, TiangZProto.encode_c2m_navigate_to({
		"target_x": x,
		"target_y": y,
		"target_z": z,
		"sequence": sequence,
	}), TiangZProto.M2C_NAVIGATE_TO, Callable(self, "_on_navigate_response"))
	return true

func navigate_input(forward: int, strafe: int, yaw: float, sequence: int) -> bool:
	if phase != "map":
		return false
	_send_rpc(TiangZProto.C2M_NAVIGATE_INPUT, TiangZProto.encode_c2m_navigate_input({
		"forward": forward,
		"strafe": strafe,
		"yaw": yaw,
		"sequence": sequence,
	}), TiangZProto.M2C_NAVIGATE_INPUT, Callable(self, "_on_navigate_response"))
	return true

func toggle_demo_door(closed: bool) -> bool:
	if phase != "map" or door_request_pending:
		return false
	door_request_pending = true
	_send_rpc(TiangZProto.C2M_TOGGLE_DEMO_DOOR, TiangZProto.encode_c2m_toggle_demo_door({"closed": closed}), TiangZProto.M2C_TOGGLE_DEMO_DOOR, Callable(self, "_on_door_response"))
	return true

func toggle_auto_attack(enabled: bool, target_unit_id: int) -> bool:
	if phase != "map" or auto_attack_request_pending:
		return false
	auto_attack_request_pending = true
	_send_rpc(TiangZProto.C2M_TOGGLE_AUTO_ATTACK, TiangZProto.encode_c2m_toggle_auto_attack({
		"enabled": enabled,
		"target_unit_id": target_unit_id,
	}), TiangZProto.M2C_TOGGLE_AUTO_ATTACK, Callable(self, "_on_auto_attack_response"))
	return true

## 发送使用道具请求；道具数量、公共CD和具体效果仍由服务端决定。
## Sends an item-use request; count, cooldowns, and effects remain server-authoritative.
func use_item(item_id: int) -> bool:
	if phase != "map" or item_request_pending:
		return false
	item_request_pending = true
	var operation_id := "item-%d-%d" % [Time.get_ticks_usec(), randi()]
	_send_rpc(TiangZProto.C2M_USE_ITEM, TiangZProto.encode_c2m_use_item({
		"item_id": item_id,
		"operation_id": operation_id,
	}), TiangZProto.M2C_USE_ITEM, Callable(self, "_on_use_item_response"))
	return true

## 发送施法请求；客户端只负责选择目标和展示读条，不在本地结算伤害。
## Sends a cast request; the client only selects a target and renders the cast, never resolves damage locally.
func cast_skill(skill_id: int, target_unit_id: int) -> bool:
	if phase != "map" or skill_request_pending:
		return false
	skill_request_pending = true
	_send_rpc(TiangZProto.C2M_CAST_SKILL, TiangZProto.encode_c2m_cast_skill({"skill_id": skill_id, "target_unit_id": target_unit_id}), TiangZProto.M2C_CAST_SKILL, Callable(self, "_on_cast_skill_response"))
	return true

## 接取任务；是否满足条件由服务端任务系统判断。
## Accepts a quest; eligibility is checked by the server quest system.
func accept_quest(quest_config_id: int) -> bool:
	if phase != "map" or quest_request_pending:
		return false
	quest_request_pending = true
	_send_rpc(TiangZProto.C2M_ACCEPT_QUEST, TiangZProto.encode_c2m_accept_quest({"quest_config_id": quest_config_id, "npc_unit_id": 0}), TiangZProto.M2C_ACCEPT_QUEST, Callable(self, "_on_accept_quest_response"))
	return true

## 从指定NPC处接取任务；服务端会再次校验NPC、距离和任务链。
## Accepts a quest from an NPC; the server rechecks NPC identity, distance, and quest chain.
func accept_quest_from_npc(quest_config_id: int, npc_unit_id: int) -> bool:
	if phase != "map" or quest_request_pending:
		return false
	quest_request_pending = true
	_send_rpc(TiangZProto.C2M_ACCEPT_QUEST, TiangZProto.encode_c2m_accept_quest({"quest_config_id": quest_config_id, "npc_unit_id": npc_unit_id}), TiangZProto.M2C_ACCEPT_QUEST, Callable(self, "_on_accept_quest_response"))
	return true

## 交付任务；奖励和任务完成状态由服务端返回。
## Completes a quest; rewards and completion state come from the server response.
func complete_quest(quest_config_id: int) -> bool:
	if phase != "map" or quest_request_pending:
		return false
	quest_request_pending = true
	_send_rpc(TiangZProto.C2M_COMPLETE_QUEST, TiangZProto.encode_c2m_complete_quest({"quest_config_id": quest_config_id, "npc_unit_id": 0}), TiangZProto.M2C_COMPLETE_QUEST, Callable(self, "_on_complete_quest_response"))
	return true

## 从指定NPC处交付任务；领取奖励不是客户端本地按钮行为。
## Turns in a quest at an NPC; claiming the reward is never a local-only button action.
func complete_quest_from_npc(quest_config_id: int, npc_unit_id: int) -> bool:
	if phase != "map" or quest_request_pending:
		return false
	quest_request_pending = true
	_send_rpc(TiangZProto.C2M_COMPLETE_QUEST, TiangZProto.encode_c2m_complete_quest({"quest_config_id": quest_config_id, "npc_unit_id": npc_unit_id}), TiangZProto.M2C_COMPLETE_QUEST, Callable(self, "_on_complete_quest_response"))
	return true

## 查看尸体掉落；窗口只展示服务端返回的当前列表，不提前删除尸体。
## Inspects corpse loot; the UI displays the server list and never deletes the corpse locally.
func inspect_loot_monster(monster_id: int) -> bool:
	if phase != "map" or loot_inspect_request_pending or monster_id == 0:
		return false
	loot_inspect_request_pending = true
	_send_rpc(TiangZProto.C2M_INSPECT_LOOT_MONSTER, TiangZProto.encode_c2m_inspect_loot_monster({"monster_id": monster_id}), TiangZProto.M2C_INSPECT_LOOT_MONSTER, Callable(self, "_on_inspect_loot_response"))
	return true

## 拾取一行或全部掉落；operation_id由调用方在一次逻辑操作内复用以保证幂等。
## Loots one row or all rows; the caller reuses operation_id across retries for idempotency.
func loot_monster(monster_id: int, operation_id: String, drop_id: int, loot_all: bool) -> bool:
	if phase != "map" or loot_request_pending or monster_id == 0:
		return false
	loot_request_pending = true
	_send_rpc(TiangZProto.C2M_LOOT_MONSTER, TiangZProto.encode_c2m_loot_monster({
		"monster_id": monster_id,
		"operation_id": operation_id,
		"drop_id": drop_id,
		"loot_all": loot_all,
	}), TiangZProto.M2C_LOOT_MONSTER, Callable(self, "_on_loot_response"))
	return true

func _connect(host: String, port: int, callback: Callable) -> void:
	if peer != null:
		peer.close()
	peer = null
	pending.clear()
	socket_opened = false
	connect_callback = callback
	peer = WebSocketPeer.new()
	var error := peer.connect_to_url("ws://%s:%d" % [host, port])
	if error != OK:
		_emit_status("连接失败：%s" % error_string(error), true)
		phase = "closed"

func _request_login_service_addr() -> void:
	phase = "login_mgr"
	_send_rpc(TiangZProto.C2S_GET_LOGIN_SERVICE_ADDR, TiangZProto.encode_c2s_get_login_service_addr({}), TiangZProto.S2C_GET_LOGIN_SERVICE_ADDR, Callable(self, "_on_login_service_addr"))

func _on_login_service_addr(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var body := TiangZProto.decode_s2c_get_login_service_addr(response.payload)
	_emit_status("LoginMgr已选择 %s:%d" % [body.ip, body.port], false)
	_connect(body.ip, body.port, Callable(self, "_request_login"))

func _request_login() -> void:
	phase = "login"
	if auth_mode == "register":
		_send_rpc(TiangZProto.C2S_REGISTER, TiangZProto.encode_c2s_register({"account": account, "password": password}), TiangZProto.S2C_REGISTER, Callable(self, "_on_register"))
	else:
		_send_rpc(TiangZProto.C2S_LOGIN, TiangZProto.encode_c2s_login({"account": account, "password": password}), TiangZProto.S2C_LOGIN, Callable(self, "_on_login"))

func _on_register(response: Dictionary) -> void:
	if not _check_response(response):
		auth_mode = "login"
		return
	var body := TiangZProto.decode_s2c_register(response.payload)
	_emit_status("注册成功：%s，正在登录" % String(body.get("account", account)), false)
	auth_mode = "login"
	_request_login()

func _request_login_gate() -> void:
	phase = "gate_login"
	_send_rpc(TiangZProto.C2G_LOGIN_GATE, TiangZProto.encode_c2g_login_gate({"account": account, "token": token}), TiangZProto.G2C_LOGIN_GATE, Callable(self, "_on_login_gate"))

func _on_login(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var body := TiangZProto.decode_s2c_login(response.payload)
	token = body.token
	_emit_status("登录成功，正在连接 Gate %s:%d" % [body.gate_ip, body.gate_port], false)
	_connect(body.gate_ip, body.gate_port, Callable(self, "_request_login_gate"))

func _on_login_gate(response: Dictionary) -> void:
	if not _check_response(response):
		return
	phase = "enter_map"
	_send_rpc(TiangZProto.C2G_ENTER_MAP, TiangZProto.encode_c2g_enter_map({"map_id": 100, "map_instance_id": 0}), TiangZProto.G2C_ENTER_MAP, Callable(self, "_on_enter_map"))

func _on_enter_map(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var snapshot := TiangZProto.decode_g2c_enter_map(response.payload)
	phase = "map"
	last_ping_ms = Time.get_ticks_msec()
	map_entered.emit(snapshot)
	_emit_status("已进入 Map %d，Unit %d" % [snapshot.map_id, snapshot.unit_id], false)
	_send_rpc(TiangZProto.C2G_MAP_SNAPSHOT_READY, TiangZProto.encode_c2g_map_snapshot_ready({"unit_id": snapshot.unit_id}), TiangZProto.G2C_MAP_SNAPSHOT_READY, Callable(self, "_on_snapshot_ready"))

func _on_snapshot_ready(response: Dictionary) -> void:
	if _check_response(response):
		var state := TiangZProto.decode_g2c_map_snapshot_ready(response.payload)
		door_changed.emit(state.demo_door_closed, false)
		_emit_status("地图快照监听已就绪", false)

func _on_navigate_response(response: Dictionary) -> void:
	if not _check_response(response):
		return
	# M2C_NavigateTo的业务字段只有路径确认；RPC错误已经在外层response中检查过。
	# M2C_NavigateTo only acknowledges the path; RPC errors were checked in the outer response.

func _on_door_response(response: Dictionary) -> void:
	door_request_pending = false
	if not _check_response(response):
		return
	var result := TiangZProto.decode_m2c_toggle_demo_door(response.payload)
	door_changed.emit(result.closed, result.changed)

func _on_ping(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var result := TiangZProto.decode_g2c_ping(response.payload)
	var now := Time.get_ticks_msec()
	ping_result.emit(now - ping_sent_at, result.server_time)

func _on_auto_attack_response(response: Dictionary) -> void:
	auto_attack_request_pending = false
	if not _check_response(response):
		return
	auto_attack_state_changed.emit(TiangZProto.decode_m2c_toggle_auto_attack(response.payload))

func _on_use_item_response(response: Dictionary) -> void:
	item_request_pending = false
	if not _check_response(response):
		return
	var result := TiangZProto.decode_m2c_use_item(response.payload)
	if result.get("item") != null:
		item_changed.emit(result.item)
	if result.get("buff") != null:
		buff_added.emit(result.buff)

func _on_cast_skill_response(response: Dictionary) -> void:
	skill_request_pending = false
	if not _check_response(response):
		return
	# M2C_CastSkill与G2C_SkillCastState共用施法字段，直接交给同一套表现状态机。
	# M2C_CastSkill and G2C_SkillCastState share cast fields, so both use one presentation state machine.
	skill_cast_state.emit(TiangZProto.decode_m2c_cast_skill(response.payload))

func _on_accept_quest_response(response: Dictionary) -> void:
	quest_request_pending = false
	if not _check_response(response):
		return
	var result := TiangZProto.decode_m2c_accept_quest(response.payload)
	quest_progress.emit({"quests": [result.quest]})

func _on_complete_quest_response(response: Dictionary) -> void:
	quest_request_pending = false
	if not _check_response(response):
		return
	var result := TiangZProto.decode_m2c_complete_quest(response.payload)
	quest_progress.emit({"quests": [], "completed": [result.get("quest_config_id", 0)]})
	_emit_status("任务完成，获得奖励 %d 件" % result.get("reward_items", []).size(), false)

func _on_inspect_loot_response(response: Dictionary) -> void:
	loot_inspect_request_pending = false
	if not _check_response(response):
		return
	loot_inspected.emit(TiangZProto.decode_m2c_inspect_loot_monster(response.payload))

func _on_loot_response(response: Dictionary) -> void:
	loot_request_pending = false
	if not _check_response(response):
		return
	var result := TiangZProto.decode_m2c_loot_monster(response.payload)
	for item in result.get("items", []):
		item_changed.emit(item)
	for quest in result.get("quests", []):
		quest_progress.emit({"quests": [quest]})
	loot_result.emit(result)

func _send_rpc(msg_code: int, payload: PackedByteArray, response_code: int, callback: Callable) -> void:
	if peer == null or peer.get_ready_state() != WebSocketPeer.STATE_OPEN:
		return
	var current_id := next_rpc_id
	next_rpc_id += 1
	var body := TiangZProto.with_rpc(current_id, payload)
	pending[current_id] = {"expected": response_code, "callback": callback, "payload": PackedByteArray()}
	peer.send(TiangZProto.frame(msg_code, body), WebSocketPeer.WRITE_MODE_BINARY)

func _handle_packet(packet: PackedByteArray) -> void:
	if packet.size() < 2:
		_emit_status("收到损坏的Godot协议包", true)
		return
	var msg_code := (int(packet[0]) << 8) | int(packet[1])
	var payload := packet.slice(2)
	if msg_code == TiangZProto.G2C_MAP_READY:
		map_ready.emit(TiangZProto.decode_g2c_map_ready(payload))
	elif msg_code == TiangZProto.G2C_ENTITY_NAVIGATE:
		navigate_push.emit(TiangZProto.decode_g2c_entity_navigate(payload))
	elif msg_code == TiangZProto.G2C_AOI_DELTA:
		aoi_delta.emit(TiangZProto.decode_g2c_aoi_delta(payload))
	elif msg_code == TiangZProto.G2C_ENTITY_ENTER:
		entity_enter.emit(TiangZProto.decode_g2c_entity_enter(payload).entity)
	elif msg_code == TiangZProto.G2C_ENTITY_LEAVE:
		entity_leave.emit(TiangZProto.decode_g2c_entity_leave(payload).unit_id)
	elif msg_code == TiangZProto.G2C_ENTITY_NUMERIC:
		entity_numeric.emit(TiangZProto.decode_g2c_entity_numeric(payload))
	elif msg_code == TiangZProto.G2C_ENTITY_STATE:
		entity_state.emit(TiangZProto.decode_g2c_entity_state(payload))
	elif msg_code == TiangZProto.G2C_DEMO_DOOR_STATE:
		door_changed.emit(TiangZProto.decode_g2c_demo_door_state(payload).closed, true)
	elif msg_code == TiangZProto.G2C_AUTO_ATTACK_STATE:
		auto_attack_state_changed.emit(TiangZProto.decode_g2c_auto_attack_state(payload))
	elif msg_code == TiangZProto.G2C_ITEM_CHANGED:
		var item_message := TiangZProto.decode_g2c_item_changed(payload)
		if item_message.get("item") != null:
			item_changed.emit(item_message.item)
	elif msg_code == TiangZProto.G2C_BUFF_ADDED:
		buff_added.emit(TiangZProto.decode_g2c_buff_added(payload).buff)
	elif msg_code == TiangZProto.G2C_BUFF_REMOVED:
		buff_removed.emit(TiangZProto.decode_g2c_buff_removed(payload))
	elif msg_code == TiangZProto.G2C_BUFF_DETAIL:
		buff_detail.emit(TiangZProto.decode_g2c_buff_detail(payload))
	elif msg_code == TiangZProto.G2C_QUEST_PROGRESS:
		quest_progress.emit(TiangZProto.decode_g2c_quest_progress(payload))
	elif msg_code == TiangZProto.G2C_SKILL_CAST_STATE:
		skill_cast_state.emit(TiangZProto.decode_g2c_skill_cast_state(payload))
	elif msg_code == TiangZProto.G2C_SKILL_PROJECTILE:
		skill_projectile.emit(TiangZProto.decode_g2c_skill_projectile(payload))
	elif msg_code == TiangZProto.G2C_SKILL_IMPACT:
		skill_impact.emit(TiangZProto.decode_g2c_skill_impact(payload))
	elif msg_code == TiangZProto.G2C_SESSION_REPLACED:
		var replaced := TiangZProto.decode_g2c_session_replaced(payload)
		session_replaced.emit(replaced)
		_emit_status("账号已在其他位置登录", true)
		phase = "closed"
	else:
		var response_id := TiangZProto.decode_rpc_id(payload)
		if pending.has(response_id):
			var request: Dictionary = pending[response_id]
			pending.erase(response_id)
			if int(request["expected"]) != msg_code:
				_emit_status("RPC响应不匹配：%d != %d" % [msg_code, request["expected"]], true)
				return
			var callback: Callable = request["callback"]
			var response := {"rpc_id": response_id, "payload": payload, "error": 0, "message": ""}
			var meta := TiangZProto.decode_error(payload)
			response["error"] = meta.get("error", 0)
			response["message"] = meta.get("message", "")
			callback.call(response)

func _check_response(response: Dictionary) -> bool:
	if int(response.get("error", 0)) != 0:
		_emit_status("请求失败：%s" % str(response.get("message", "")), true)
		return false
	return true

func _has_pending_response(response_code: int) -> bool:
	for request in pending.values():
		if int(request["expected"]) == response_code:
			return true
	return false

func _emit_status(text: String, is_error: bool) -> void:
	status_changed.emit(text, is_error)
