import { readFile, mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const configRoot = path.join(root, "src/model/generated/config");
const outputRoot = path.join(root, "src/model/generated/facade");
const schema = await readFile(path.join(configRoot, "schema.ts"), "utf8");
const fingerprint = createHash("sha256").update(schema.replaceAll("\r\n", "\n")).digest("hex");
const configManifest = JSON.parse(await readFile(path.join(root, "generated/config-package/game-config.manifest.json"), "utf8"));
let facade = createServerFacade(fingerprint).replace('from "./schema"', 'from "../config/schema"');
const tablesStart = facade.indexOf("    const tables = new Tables");
const tablesEnd = facade.indexOf("    const previousFingerprint", tablesStart);
const factory = facade.slice(tablesStart, tablesEnd)
  .replace("const candidate: GameConfigSnapshot", "const candidate: GameConfigTables")
  .replace(/      (?:dataFingerprint|hotDataFingerprint|coldDataFingerprint): manifest\.\w+,\n/g, "");
if (tablesStart < 0 || tablesEnd < 0) throw new Error("unexpected config facade template");
facade = facade.slice(0, tablesStart) + "    const candidate: GameConfigSnapshot = Object.freeze({ ...CreateGameConfigTables(rawData), dataFingerprint: manifest.dataFingerprint, hotDataFingerprint: manifest.hotDataFingerprint, coldDataFingerprint: manifest.coldDataFingerprint });\n" + facade.slice(tablesEnd);
facade = facade.replace("function validateSnapshot(snapshot: GameConfigSnapshot)", "function validateSnapshot(snapshot: GameConfigTables)");
facade = facade.replaceAll("snapshot: GameConfigSnapshot,", "snapshot: GameConfigTables,");
facade += '\nexport type GameConfigTables = Omit<GameConfigSnapshot, "dataFingerprint" | "hotDataFingerprint" | "coldDataFingerprint">;\n' +
  `export function CreateGameConfigTables(rawData: Readonly<Record<string, unknown>>): GameConfigTables {\n${factory}    return candidate;\n}\n`;
facade = facade.replace("export const GameConfigs = Object.freeze({", "export class GameConfigs {");
facade = facade.replace(/  get (\w+)\(\) \{ return GameConfigRegistry.RequireCurrent\(\)\.(\w+); \},/g, "  static get $1() { return GameConfigRegistry.RequireCurrent().$2; }");
facade = facade.replace("});\n\nfunction validateSnapshot", "}\n\nfunction validateSnapshot");
facade = facade.replace("  static RequireCurrent(): GameConfigSnapshot {", `  static RequireCurrent(): GameConfigSnapshot {
    let installed;
    try { installed = ModuleConfigRegistry.Get("org.tiangz.mmorpg"); }
    catch (error) { if (!this.current) throw error; }
    if (installed && this.current?.dataFingerprint !== installed.dataFingerprint) {
      this.current = Object.freeze({ ...CreateGameConfigTables(installed.tables), dataFingerprint: installed.dataFingerprint,
        hotDataFingerprint: installed.dataFingerprint, coldDataFingerprint: ${JSON.stringify(configManifest.coldDataFingerprint)} });
    }`);
facade = facade.replace('import { ActionType', 'import { ModuleConfigRegistry } from "#tiangz/core";\nimport { ActionType');
await mkdir(outputRoot, { recursive: true });
await writeFile(path.join(outputRoot, "GameConfigs.ts"), facade);
await writeFile(path.join(outputRoot, "index.ts"), '// Generated by tools/codegen_game_config.mjs. Do not edit.\nexport * from "./GameConfigs";\nexport * from "../config/schema";\n');
console.log("[mmorpg-config] generated typed facade; data ownership remains ModuleConfigRegistry");

function createServerFacade(schemaFingerprint) {
  return `// Generated by tools/codegen_game_config.mjs for server. Do not edit.
import { ActionType, SkillAutoAttackPolicy, SkillDelivery, SkillMovementPolicy, SkillTargetRelation, SpatialMode, Tables, type game } from "./schema";

export interface GameConfigManifest {
  readonly formatVersion: number;
  readonly schemaFingerprint: string;
  readonly dataFingerprint: string;
  readonly hotDataFingerprint: string;
  readonly coldDataFingerprint: string;
}

export interface GameConfigInstallResult {
  readonly previousFingerprint?: string;
  readonly dataFingerprint: string;
  readonly hotDataFingerprint: string;
  readonly coldDataFingerprint: string;
}

class ConfigTable<T extends { readonly id: number }> {
  private readonly byId: ReadonlyMap<number, T>;
  private readonly values: readonly T[];

  constructor(values: readonly T[]) {
    const copy = values.map((value) => Object.freeze(value));
    this.values = Object.freeze(copy);
    this.byId = new Map(copy.map((value) => [value.id, value]));
  }

  Get(id: number): T {
    const value = this.byId.get(id);
    if (!value) throw new Error(\`game config not found: id=\${id}\`);
    return value;
  }

  TryGet(id: number): T | undefined {
    return this.byId.get(id);
  }

  GetAll(): readonly T[] {
    return this.values;
  }
}

export type ItemConfig = game.ItemConfig;
export type BuffConfig = game.BuffConfig;
export type MapConfig = game.MapConfig;
export type PlayerConfig = game.PlayerConfig;
export type AoiConfig = game.AoiConfig;
export type AoiSyncTierConfig = game.AoiSyncTierConfig;
export type MonsterConfig = game.MonsterConfig;
export type MonsterAreaConfig = game.MonsterAreaConfig;
export type DropTableConfig = game.DropTableConfig;
export type SkillConfig = game.SkillConfig;
export type SkillEffectConfig = game.SkillEffectConfig;
export type QuestConfig = game.QuestConfig;
export type QuestObjectiveConfig = game.QuestObjectiveConfig;

interface GameConfigSnapshot {
  readonly dataFingerprint: string;
  readonly hotDataFingerprint: string;
  readonly coldDataFingerprint: string;
  readonly ItemConfig: ConfigTable<game.ItemConfig>;
  readonly BuffConfig: ConfigTable<game.BuffConfig>;
  readonly MapConfig: ConfigTable<game.MapConfig>;
  readonly PlayerConfig: ConfigTable<game.PlayerConfig>;
  readonly AoiConfig: ConfigTable<game.AoiConfig>;
  readonly AoiSyncTierConfig: ConfigTable<game.AoiSyncTierConfig>;
  readonly MonsterConfig: ConfigTable<game.MonsterConfig>;
  readonly MonsterAreaConfig: ConfigTable<game.MonsterAreaConfig>;
  readonly DropTableConfig: ConfigTable<game.DropTableConfig>;
  readonly SkillConfig: ConfigTable<game.SkillConfig>;
  readonly SkillEffectConfig: ConfigTable<game.SkillEffectConfig>;
  readonly QuestConfig: ConfigTable<game.QuestConfig>;
  readonly QuestObjectiveConfig: ConfigTable<game.QuestObjectiveConfig>;
}

export const GameConfigSchemaFingerprint = "${schemaFingerprint}";

export class GameConfigRegistry {
  private static current: GameConfigSnapshot | undefined;

  static get CurrentFingerprint(): string | undefined {
    return this.current?.dataFingerprint;
  }

  static get CurrentColdFingerprint(): string | undefined {
    return this.current?.coldDataFingerprint;
  }

  static Install(manifestJson: string, dataJson: string): GameConfigInstallResult {
    const manifest = JSON.parse(manifestJson) as GameConfigManifest;
    if (manifest.formatVersion !== 2) {
      throw new Error(\`unsupported game config manifest format: \${manifest.formatVersion}\`);
    }
    if (manifest.schemaFingerprint !== GameConfigSchemaFingerprint) {
      throw new Error(
        \`game config schema mismatch: model=\${GameConfigSchemaFingerprint}, candidate=\${manifest.schemaFingerprint}\`,
      );
    }
    for (const [name, fingerprint] of Object.entries({
      dataFingerprint: manifest.dataFingerprint,
      hotDataFingerprint: manifest.hotDataFingerprint,
      coldDataFingerprint: manifest.coldDataFingerprint,
    })) {
      if (!/^[0-9a-f]{64}$/.test(fingerprint)) {
        throw new Error(\`game config \${name} must be lowercase sha256\`);
      }
    }
    if (
      this.current !== undefined &&
      manifest.coldDataFingerprint !== this.current.coldDataFingerprint
    ) {
      throw new Error(
        \`cold game config changed: active=\${this.current.coldDataFingerprint}, candidate=\${manifest.coldDataFingerprint}; rebuild and restart the Process\`,
      );
    }

    const rawData = JSON.parse(dataJson) as Record<string, unknown>;
    const tables = new Tables((file) => {
      const value = rawData[file];
      if (value === undefined) throw new Error(\`game config data not found: \${file}\`);
      return value;
    });
    const candidate: GameConfigSnapshot = Object.freeze({
      dataFingerprint: manifest.dataFingerprint,
      hotDataFingerprint: manifest.hotDataFingerprint,
      coldDataFingerprint: manifest.coldDataFingerprint,
      ItemConfig: new ConfigTable<game.ItemConfig>(tables.TbItemConfig.getDataList()),
      BuffConfig: new ConfigTable<game.BuffConfig>(tables.TbBuffConfig.getDataList()),
      MapConfig: new ConfigTable<game.MapConfig>(tables.TbMapConfig.getDataList()),
      PlayerConfig: new ConfigTable<game.PlayerConfig>(tables.TbPlayerConfig.getDataList()),
      AoiConfig: new ConfigTable<game.AoiConfig>(tables.TbAoiConfig.getDataList()),
      AoiSyncTierConfig: new ConfigTable<game.AoiSyncTierConfig>(tables.TbAoiSyncTierConfig.getDataList()),
      MonsterConfig: new ConfigTable<game.MonsterConfig>(tables.TbMonsterConfig.getDataList()),
      MonsterAreaConfig: new ConfigTable<game.MonsterAreaConfig>(tables.TbMonsterAreaConfig.getDataList()),
      DropTableConfig: new ConfigTable<game.DropTableConfig>(tables.TbDropTableConfig.getDataList()),
      SkillConfig: new ConfigTable<game.SkillConfig>(tables.TbSkillConfig.getDataList()),
      SkillEffectConfig: new ConfigTable<game.SkillEffectConfig>(tables.TbSkillEffectConfig.getDataList()),
      QuestConfig: new ConfigTable<game.QuestConfig>(tables.TbQuestConfig.getDataList()),
      QuestObjectiveConfig: new ConfigTable<game.QuestObjectiveConfig>(tables.TbQuestObjectiveConfig.getDataList()),
    });
    validateSnapshot(candidate);

    const previousFingerprint = this.current?.dataFingerprint;
    this.current = candidate;
    return {
      ...(previousFingerprint ? { previousFingerprint } : {}),
      dataFingerprint: candidate.dataFingerprint,
      hotDataFingerprint: candidate.hotDataFingerprint,
      coldDataFingerprint: candidate.coldDataFingerprint,
    };
  }

  static RequireCurrent(): GameConfigSnapshot {
    if (!this.current) throw new Error("game config data is not installed");
    return this.current;
  }
}

export const GameConfigs = Object.freeze({
  get ItemConfig() { return GameConfigRegistry.RequireCurrent().ItemConfig; },
  get BuffConfig() { return GameConfigRegistry.RequireCurrent().BuffConfig; },
  get MapConfig() { return GameConfigRegistry.RequireCurrent().MapConfig; },
  get PlayerConfig() { return GameConfigRegistry.RequireCurrent().PlayerConfig; },
  get AoiConfig() { return GameConfigRegistry.RequireCurrent().AoiConfig; },
  get AoiSyncTierConfig() { return GameConfigRegistry.RequireCurrent().AoiSyncTierConfig; },
  get MonsterConfig() { return GameConfigRegistry.RequireCurrent().MonsterConfig; },
  get MonsterAreaConfig() { return GameConfigRegistry.RequireCurrent().MonsterAreaConfig; },
  get DropTableConfig() { return GameConfigRegistry.RequireCurrent().DropTableConfig; },
  get SkillConfig() { return GameConfigRegistry.RequireCurrent().SkillConfig; },
  get SkillEffectConfig() { return GameConfigRegistry.RequireCurrent().SkillEffectConfig; },
  get QuestConfig() { return GameConfigRegistry.RequireCurrent().QuestConfig; },
  get QuestObjectiveConfig() { return GameConfigRegistry.RequireCurrent().QuestObjectiveConfig; },
});

function validateSnapshot(snapshot: GameConfigSnapshot): void {
  for (const item of snapshot.ItemConfig.GetAll()) {
    if (
      !Number.isSafeInteger(item.cooldownMs) || item.cooldownMs < 0 ||
      !Number.isSafeInteger(item.globalCooldownMs) || item.globalCooldownMs < 0
    ) {
      throw new Error(\`item config \${item.id} has invalid cooldown values\`);
    }
    if (!Number.isSafeInteger(item.useEffect) || item.useEffect < 0 || item.useEffect > 2) {
      throw new Error(\`item config \${item.id} has unsupported use effect \${item.useEffect}\`);
    }
    if (!item.useParams.every(Number.isSafeInteger)) {
      throw new Error(\`item config \${item.id} contains a non-integer use parameter\`);
    }
    if (item.useEffect === 0 && item.useParams.length !== 0) {
      throw new Error(\`item config \${item.id} cannot carry parameters when useEffect is 0\`);
    }
    if (item.useEffect === 1) {
      if (item.useParams.length !== 1 || !snapshot.BuffConfig.TryGet(item.useParams[0])) {
        throw new Error(\`item config \${item.id} AddBuff requires one valid BuffConfig id\`);
      }
    }
    if (item.useEffect === 2) {
      if (item.useParams.length === 0) {
        throw new Error(\`item config \${item.id} ExecuteAction requires [actionType, ...parameters]\`);
      }
      validateActionConfig(
        \`item config \${item.id}\`,
        "use",
        item.useParams[0],
        item.useParams.slice(1),
        false,
        snapshot,
      );
    }
  }
  for (const quest of snapshot.QuestConfig.GetAll()) {
    if (quest.objectiveIds.length === 0 || new Set(quest.objectiveIds).size !== quest.objectiveIds.length) {
      throw new Error(\`quest config \${quest.id} needs unique objectives\`);
    }
    for (const objectiveId of quest.objectiveIds) {
      const objective = snapshot.QuestObjectiveConfig.TryGet(objectiveId);
      if (!objective || objective.questConfigId !== quest.id) {
        throw new Error(\`quest config \${quest.id} references invalid objective \${objectiveId}\`);
      }
    }
    if (!Number.isSafeInteger(quest.minimumLevel) || quest.minimumLevel < 1) {
      throw new Error(\`quest config \${quest.id} has invalid minimum level \${quest.minimumLevel}\`);
    }
    if (new Set(quest.requiredQuestIds).size !== quest.requiredQuestIds.length) {
      throw new Error(\`quest config \${quest.id} has duplicate prerequisites\`);
    }
    for (const requiredQuestId of quest.requiredQuestIds) {
      if (requiredQuestId === quest.id || !snapshot.QuestConfig.TryGet(requiredQuestId)) {
        throw new Error(\`quest config \${quest.id} references invalid prerequisite \${requiredQuestId}\`);
      }
    }
    if (quest.autoAccept && quest.requiredQuestIds.length !== 0) {
      throw new Error(\`auto-accept quest \${quest.id} cannot require completed quests\`);
    }
    validateActionConfig(\`QuestConfig \${quest.id}\`, "reward", quest.rewardActionType, quest.rewardActionParams, false, snapshot);
  }
  const visitingQuests = new Set<number>();
  const visitedQuests = new Set<number>();
  const visitQuest = (questId: number): void => {
    if (visitedQuests.has(questId)) return;
    if (visitingQuests.has(questId)) throw new Error(\`quest prerequisite cycle contains \${questId}\`);
    visitingQuests.add(questId);
    for (const requiredQuestId of snapshot.QuestConfig.Get(questId).requiredQuestIds) visitQuest(requiredQuestId);
    visitingQuests.delete(questId);
    visitedQuests.add(questId);
  };
  for (const quest of snapshot.QuestConfig.GetAll()) visitQuest(quest.id);
  for (const objective of snapshot.QuestObjectiveConfig.GetAll()) {
    if (!snapshot.QuestConfig.TryGet(objective.questConfigId) || objective.objectiveType < 1 || objective.objectiveType > 4 || objective.targetConfigId <= 0 || objective.requiredCount <= 0) {
      throw new Error(\`quest objective \${objective.id} has invalid owner, type, target, or count\`);
    }
  }
  for (const buff of snapshot.BuffConfig.GetAll()) {
    if (buff.description.trim().length === 0) {
      throw new Error(\`buff config \${buff.id} needs a non-empty server description\`);
    }
    if (
      !Number.isSafeInteger(buff.durationSeconds) || buff.durationSeconds < 0 ||
      !Number.isSafeInteger(buff.tickIntervalMs) || buff.tickIntervalMs < 0
    ) {
      throw new Error(\`buff config \${buff.id} has invalid duration or tick interval\`);
    }
    if (!Number.isSafeInteger(buff.stackGroup) || buff.stackGroup <= 0) {
      throw new Error(\`buff config \${buff.id} needs a positive stack group\`);
    }
    if (buff.stackScope < 1 || buff.stackScope > 2) {
      throw new Error(\`buff config \${buff.id} has unsupported stack scope \${buff.stackScope}\`);
    }
    if (buff.conflictPolicy < 1 || buff.conflictPolicy > 5) {
      throw new Error(\`buff config \${buff.id} has unsupported conflict policy \${buff.conflictPolicy}\`);
    }
    if (!Number.isSafeInteger(buff.conflictPriority) || buff.conflictPriority < 0) {
      throw new Error(\`buff config \${buff.id} has invalid conflict priority\`);
    }
    if (buff.conflictPolicy === 5 && buff.conflictPriority <= 0) {
      throw new Error(\`buff config \${buff.id} HigherWins requires a positive conflict priority\`);
    }
    if (buff.refreshTickPolicy < 1 || buff.refreshTickPolicy > 2) {
      throw new Error(\`buff config \${buff.id} has unsupported refresh Tick policy\`);
    }
    if (buff.refreshRuntimeState < 1 || buff.refreshRuntimeState > 2) {
      throw new Error(\`buff config \${buff.id} has unsupported refresh runtime-state policy\`);
    }
    validateActionConfig(
      "BuffConfig " + buff.id,
      "add",
      buff.addActionType,
      buff.addActionParams,
      false,
      snapshot,
    );
    validateActionConfig(
      "BuffConfig " + buff.id,
      "tick",
      buff.tickActionType,
      buff.tickActionParams,
      false,
      snapshot,
    );
    validateActionConfig(
      "BuffConfig " + buff.id,
      "remove",
      buff.removeActionType,
      buff.removeActionParams,
      true,
      snapshot,
    );
    if (buff.tickIntervalMs === 0 && buff.tickActionType !== 0) {
      throw new Error(\`buff config \${buff.id} has a Tick Action but no tick interval\`);
    }
    if (buff.tickIntervalMs > 0 && buff.tickActionType === 0) {
      throw new Error(\`buff config \${buff.id} has a tick interval but no Tick Action\`);
    }
  }
  const effectsBySkill = new Map<number, game.SkillEffectConfig[]>();
  for (const effect of snapshot.SkillEffectConfig.GetAll()) {
    if (!effect.skillId_ref) {
      throw new Error(\`skill effect \${effect.id} contains a missing SkillConfig reference\`);
    }
    if (!Number.isSafeInteger(effect.order) || effect.order <= 0) {
      throw new Error(\`skill effect \${effect.id} needs a positive integer order\`);
    }
    if (effect.target < 1 || effect.target > 2) {
      throw new Error(\`skill effect \${effect.id} has unsupported target \${effect.target}\`);
    }
    if (effect.description.trim().length === 0) {
      throw new Error(\`skill effect \${effect.id} needs a non-empty description\`);
    }
    if (effect.actionType === 0) {
      throw new Error(\`skill effect \${effect.id} cannot use ActionType.None\`);
    }
    validateActionConfig(
      \`SkillEffectConfig \${effect.id}\`,
      "resolve",
      effect.actionType,
      effect.actionParams,
      false,
      snapshot,
      true,
    );
    const effects = effectsBySkill.get(effect.skillId) ?? [];
    if (effects.some((current) => current.order === effect.order)) {
      throw new Error(\`skill config \${effect.skillId} has duplicate effect order \${effect.order}\`);
    }
    effects.push(effect);
    effectsBySkill.set(effect.skillId, effects);
  }
  for (const skill of snapshot.SkillConfig.GetAll()) {
    const orderedEffects = [...(effectsBySkill.get(skill.id) ?? [])]
      .sort((left, right) => left.order - right.order || left.id - right.id);
    let hasResolvedDamage = false;
    for (const effect of orderedEffects) {
      if (effect.actionType === 4) hasResolvedDamage = true;
      if (effect.actionType !== 8) continue;
      if (!hasResolvedDamage) {
        throw new Error(\`skill config \${skill.id} HealFromResolvedDamagePercent must follow DealDamage\`);
      }
      if (effect.target !== 1) {
        throw new Error(\`skill config \${skill.id} HealFromResolvedDamagePercent must target Caster\`);
      }
    }
    if (skill.description.trim().length === 0) {
      throw new Error(\`skill config \${skill.id} needs a non-empty description\`);
    }
    if (
      !Number.isSafeInteger(skill.castTimeMs) || skill.castTimeMs < 0 ||
      !Number.isSafeInteger(skill.cooldownMs) || skill.cooldownMs < 0 ||
      !Number.isSafeInteger(skill.globalCooldownMs) || skill.globalCooldownMs < 0 ||
      !Number.isFinite(skill.rangeMeters) || skill.rangeMeters <= 0 ||
      !Number.isSafeInteger(skill.queueWindowMs) || skill.queueWindowMs < 0 ||
      !Number.isSafeInteger(skill.channelTickMs) || skill.channelTickMs < 0 ||
      !Number.isSafeInteger(skill.channelTicks) || skill.channelTicks < 0
    ) {
      throw new Error(\`skill config \${skill.id} has invalid cast, cooldown, range, queue, or channel values\`);
    }
    if (skill.targetRelation < SkillTargetRelation.Enemy || skill.targetRelation > SkillTargetRelation.Friendly) {
      throw new Error(\`skill config \${skill.id} has unsupported target relation\`);
    }
    if (skill.movementPolicy < SkillMovementPolicy.Allow || skill.movementPolicy > SkillMovementPolicy.InterruptWhileCasting) {
      throw new Error(\`skill config \${skill.id} has unsupported movement policy\`);
    }
    if (skill.autoAttackPolicy < SkillAutoAttackPolicy.Keep || skill.autoAttackPolicy > SkillAutoAttackPolicy.Cancel) {
      throw new Error(\`skill config \${skill.id} has unsupported auto-attack policy\`);
    }
    if (skill.delivery === SkillDelivery.Direct) {
      if (skill.projectileSpeedMetersPerSecond !== 0) {
        throw new Error(\`direct skill config \${skill.id} must use zero projectile speed\`);
      }
    } else if (skill.delivery === SkillDelivery.Projectile) {
      if (!Number.isFinite(skill.projectileSpeedMetersPerSecond) || skill.projectileSpeedMetersPerSecond <= 0) {
        throw new Error(\`projectile skill config \${skill.id} needs a positive projectile speed\`);
      }
    } else {
      throw new Error(\`skill config \${skill.id} has unsupported delivery \${skill.delivery}\`);
    }
    if ((skill.channelTickMs === 0) !== (skill.channelTicks === 0)) {
      throw new Error(\`skill config \${skill.id} must configure channel tick interval and count together\`);
    }
    if (skill.channelTicks > 0 && (skill.delivery !== SkillDelivery.Direct || skill.castTimeMs < skill.channelTickMs * skill.channelTicks)) {
      throw new Error(\`skill config \${skill.id} channel must be direct and fit inside cast time\`);
    }
    if (
      skill.requiredAbsentBuffConfigId > 0 &&
      !snapshot.BuffConfig.TryGet(skill.requiredAbsentBuffConfigId)
    ) {
      throw new Error(\`skill config \${skill.id} references a missing blocking BuffConfig\`);
    }
    if ((effectsBySkill.get(skill.id) ?? []).length === 0) {
      throw new Error(\`skill config \${skill.id} needs at least one SkillEffectConfig row\`);
    }
  }
  const tiersByAoi = new Map<number, game.AoiSyncTierConfig[]>();
  for (const tier of snapshot.AoiSyncTierConfig.GetAll()) {
    if (!tier.aoiConfigId_ref) {
      throw new Error(\`AOI sync tier \${tier.id} contains a missing AOI reference\`);
    }
    if (!isPositiveOdd(tier.rangeGrids) || !Number.isSafeInteger(tier.syncHz) || tier.syncHz <= 0) {
      throw new Error(\`AOI sync tier \${tier.id} needs a positive odd range and positive integer Hz\`);
    }
    const tiers = tiersByAoi.get(tier.aoiConfigId) ?? [];
    tiers.push(tier);
    tiersByAoi.set(tier.aoiConfigId, tiers);
  }
  for (const aoi of snapshot.AoiConfig.GetAll()) {
    if (
      !Number.isSafeInteger(aoi.gridSizeCells) || aoi.gridSizeCells <= 0 ||
      !isPositiveOdd(aoi.enterRangeGrids) || !isPositiveOdd(aoi.detachRangeGrids) ||
      aoi.enterRangeGrids > aoi.detachRangeGrids
    ) {
      throw new Error(\`AOI config \${aoi.id} needs positive Grid size and nested odd Enter/Detach ranges\`);
    }
    const tiers = (tiersByAoi.get(aoi.id) ?? []).sort((left, right) => left.rangeGrids - right.rangeGrids);
    if (tiers.length === 0) {
      throw new Error(\`AOI config \${aoi.id} needs at least one sync tier\`);
    }
    for (let index = 0; index < tiers.length; index += 1) {
      const tier = tiers[index];
      if (tier.rangeGrids > aoi.detachRangeGrids) {
        throw new Error(\`AOI sync tier \${tier.id} exceeds Detach range\`);
      }
      if (index > 0) {
        const previous = tiers[index - 1];
        if (tier.rangeGrids === previous.rangeGrids || tier.syncHz > previous.syncHz) {
          throw new Error(\`AOI config \${aoi.id} sync tiers must widen uniquely without increasing Hz\`);
        }
      }
    }
    if (tiers[tiers.length - 1].rangeGrids !== aoi.detachRangeGrids) {
      throw new Error(\`AOI config \${aoi.id} outermost sync tier must equal Detach range\`);
    }
  }
  for (const map of snapshot.MapConfig.GetAll()) {
    if (![map.spawnX, map.spawnY, map.spawnZ, map.spawnYaw, map.cellSizeMeters].every(Number.isFinite)) {
      throw new Error(\`map config \${map.id} contains a non-finite spatial value\`);
    }
    if (!map.aoiConfigId_ref || map.cellSizeMeters <= 0) {
      throw new Error(\`map config \${map.id} needs a positive Cell size and valid AOI config\`);
    }
    if (
      map.widthCells < 3 || map.depthCells < 3 ||
      map.widthCells % map.aoiConfigId_ref.gridSizeCells !== 0 ||
      map.depthCells % map.aoiConfigId_ref.gridSizeCells !== 0
    ) {
      throw new Error(\`map config \${map.id} dimensions must align to its AOI Grid\`);
    }
    if (
      !Number.isSafeInteger(map.entryPlayersPerTick) || map.entryPlayersPerTick <= 0 ||
      !Number.isSafeInteger(map.entryQueueCapacity) ||
      map.entryQueueCapacity < map.entryPlayersPerTick
    ) {
      throw new Error(\`map config \${map.id} has invalid player-entry admission limits\`);
    }
    if (map.spatialMode === SpatialMode.Grid2D) {
      // Grid2D没有额外资源字段；公共地图边界校验已经覆盖Cell与AOI Grid对齐。
    } else if (map.spatialMode === SpatialMode.NavMesh3D) {
      if (!map.navigationAsset || !map.navigationVersion || !/^[0-9a-f]{64}$/.test(map.navigationHash)) {
        throw new Error(\`NavMesh3D map config \${map.id} needs an asset, version, and lowercase SHA-256\`);
      }
    } else {
      throw new Error(\`map config \${map.id} has unsupported spatial mode \${map.spatialMode}\`);
    }
  }
  for (const player of snapshot.PlayerConfig.GetAll()) {
    if (!player.initialMapId_ref || !player.initialItemConfigId_ref) {
      throw new Error(\`player config \${player.id} contains a missing reference\`);
    }
    if (player.initialHp < 0 || player.maxHp <= 0 || player.initialHp > player.maxHp) {
      throw new Error(\`player config \${player.id} has invalid hp values\`);
    }
    if (
      player.moveSpeed <= 0 ||
      player.initialItemCount < 0 ||
      player.attackRange <= 0 ||
      player.attackRange > 4
    ) {
      throw new Error(\`player config \${player.id} has invalid movement, combat, or item values\`);
    }
  }
  for (const monster of snapshot.MonsterConfig.GetAll()) {
    if (
      monster.maxHp <= 0 ||
      monster.attackDamage < 0 ||
      monster.moveSpeed <= 0 ||
      monster.attackRange <= 0 ||
      monster.attackRange > 4 ||
      !Number.isSafeInteger(monster.attackIntervalMs) ||
      monster.attackIntervalMs <= 0 ||
      !Number.isSafeInteger(monster.respawnSeconds) ||
      monster.respawnSeconds < 0 ||
      (monster.attackMode !== 0 && monster.attackMode !== 1) ||
      monster.skillId < 0
    ) {
      throw new Error(\`monster config \${monster.id} has invalid combat values\`);
    }
  }
  const dropTableIds = new Set(snapshot.DropTableConfig.GetAll().map((drop) => drop.dropTableId));
  for (const drop of snapshot.DropTableConfig.GetAll()) {
    const itemDrop = Number.isSafeInteger(drop.itemConfigId) && drop.itemConfigId > 0 &&
      Boolean(snapshot.ItemConfig.TryGet(drop.itemConfigId)) &&
      Number.isSafeInteger(drop.minCount) && drop.minCount > 0 &&
      Number.isSafeInteger(drop.maxCount) && drop.maxCount >= drop.minCount && drop.gold === 0;
    const currencyDrop = drop.itemConfigId === 0 && drop.minCount === 0 && drop.maxCount === 0 &&
      Number.isSafeInteger(drop.gold) && drop.gold > 0 && drop.questObjectiveId === 0;
    if (
      !Number.isSafeInteger(drop.dropTableId) || drop.dropTableId <= 0 ||
      (!itemDrop && !currencyDrop) ||
      !Number.isSafeInteger(drop.chancePermille) || drop.chancePermille < 0 || drop.chancePermille > 1000 ||
      !Number.isSafeInteger(drop.questObjectiveId) || drop.questObjectiveId < 0
    ) {
      throw new Error(\`drop table row \${drop.id} has invalid item/currency, count, chance, or objective values\`);
    }
    if (drop.questObjectiveId > 0) {
      const objective = snapshot.QuestObjectiveConfig.TryGet(drop.questObjectiveId);
      if (!objective || objective.objectiveType !== 4 || objective.targetConfigId !== drop.itemConfigId) {
        throw new Error(\`drop table row \${drop.id} references an incompatible CollectItem objective\`);
      }
    }
  }
  for (const monster of snapshot.MonsterConfig.GetAll()) {
    if (monster.dropTableId > 0 && !dropTableIds.has(monster.dropTableId)) {
      throw new Error(\`monster config \${monster.id} references missing drop table \${monster.dropTableId}\`);
    }
  }
  for (const area of snapshot.MonsterAreaConfig.GetAll()) {
    if (!area.mapConfigId_ref || !area.monsterConfigId_ref) {
      throw new Error(\`monster spawn slot \${area.id} contains a missing reference\`);
    }
    if (
      ![area.spawnX, area.spawnY, area.spawnZ, area.spawnYaw].every(Number.isFinite) ||
      typeof area.initialSpawn !== "boolean"
    ) {
      throw new Error(\`monster spawn slot \${area.id} has invalid spatial or lifecycle values\`);
    }
  }
}

function validateActionConfig(
  owner: string,
  phase: string,
  type: number,
  parameters: readonly number[],
  allowEmptyRemove: boolean,
  snapshot: GameConfigSnapshot,
  allowResolvedDamage = false,
): void {
  if (!Number.isSafeInteger(type) || type < ActionType.None || type >= ActionType.Max) {
    throw new Error(\`\${owner} has unsupported \${phase} Action type \${type}\`);
  }
  if (!parameters.every(Number.isSafeInteger)) {
    throw new Error(\`\${owner} has non-integer \${phase} Action parameters\`);
  }
  if (type === 8 && !allowResolvedDamage) {
    throw new Error(\`\${owner} \${phase} HealFromResolvedDamagePercent is only valid in SkillEffectConfig\`);
  }
  const expected = type === 0
    ? 0
    : type === 1
      ? 2
      : type === 2
        ? 1
        : type === 3
          ? allowEmptyRemove ? undefined : 1
          : type === 4
            ? 2
            : type === 6
              ? 1
              : type === 7
                ? 2
                : type === 8
                  ? 1
                : undefined;
  if (expected !== undefined && parameters.length !== expected) {
    throw new Error(\`\${owner} \${phase} Action expects \${expected} parameters\`);
  }
  if (type === 3 && expected === undefined && parameters.length > 1) {
    throw new Error(\`\${owner} \${phase} RemoveBuff expects zero or one parameter\`);
  }
  if (type === 5 && (parameters.length < 1 || parameters.length > 2)) {
    throw new Error(\`\${owner} \${phase} RegisterDamageAbsorber expects one or two parameters\`);
  }
  if (type === 9 && (parameters.length === 0 || parameters.length % 2 !== 0)) {
    throw new Error(\`\${owner} \${phase} ChangeNumericBatch expects one or more [numericType, delta] pairs\`);
  }
  if (type === 10 && (parameters.length === 0
    || parameters.some((value) => value <= 0)
    || new Set(parameters).size !== parameters.length)) {
    throw new Error(\`\${owner} \${phase} RemoveBuffsByEffectTags needs unique positive effect tags\`);
  }
  if (type === 1) {
    const numericType = parameters[0];
    if (numericType <= 0 || (numericType >= 1_000 && numericType <= 9_999)) {
      throw new Error(\`\${owner} \${phase} ChangeNumeric targets an invalid or derived NumericType\`);
    }
  }
  if (type === 9) {
    const seenNumericTypes = new Set<number>();
    for (let index = 0; index < parameters.length; index += 2) {
      const numericType = parameters[index];
      if (numericType === 1) {
        throw new Error(\`\${owner} \${phase} ChangeNumericBatch cannot target CurrentHp; use Heal or DealDamage\`);
      }
      if (numericType <= 0 || (numericType >= 1_000 && numericType <= 9_999)) {
        throw new Error(\`\${owner} \${phase} ChangeNumericBatch targets an invalid or derived NumericType\`);
      }
      if (seenNumericTypes.has(numericType)) {
        throw new Error(\`\${owner} \${phase} ChangeNumericBatch contains duplicate NumericType\`);
      }
      seenNumericTypes.add(numericType);
    }
  }
  if (type === 2 && !snapshot.BuffConfig.TryGet(parameters[0])) {
    throw new Error(\`\${owner} \${phase} AddBuff references a missing BuffConfig\`);
  }
  if (type === 3 && parameters.length === 1 && parameters[0] <= 0) {
    throw new Error(\`\${owner} \${phase} RemoveBuff needs a positive runtime Buff instance id\`);
  }
  if (type === 4) {
    if (parameters[0] < 0 || parameters[1] < 1 || parameters[1] > 5) {
      throw new Error(\`\${owner} \${phase} DealDamage needs [non-negative amount, valid DamageSchool]\`);
    }
  }
  if (type === 5 && (parameters[0] <= 0 || (parameters[1] ?? 0) < 0)) {
    throw new Error(\`\${owner} \${phase} RegisterDamageAbsorber needs positive amount and non-negative priority\`);
  }
  if (type === 6 && parameters[0] < 0) {
    throw new Error(\`\${owner} \${phase} Heal needs a non-negative amount\`);
  }
  if (type === 7 && (!snapshot.ItemConfig.TryGet(parameters[0]) || parameters[1] <= 0)) {
    throw new Error(\`\${owner} \${phase} GrantItem needs [valid ItemConfig, positive count]\`);
  }
  if (type === 8 && parameters[0] < 0) {
    throw new Error(\`\${owner} \${phase} HealFromResolvedDamagePercent needs a non-negative percent\`);
  }
}

function isPositiveOdd(value: number): boolean {
  return Number.isSafeInteger(value) && value > 0 && value % 2 === 1;
}
`;
}

/** 在写出任何Generated文件前校验地图与AOI冷配置，避免无效空间数据拖到Runtime启动才失败。 / Validates cold Map/AOI data before writing Generated files. */
