import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { createClientFacade, readReloadPolicies, partitionData, validateGeneratedSpatialData, validateGeneratedActionAndSkillData } from "./config_rules.mjs";

const root = path.resolve(import.meta.dirname, "..");
const server = JSON.parse(await readFile(path.join(root, "game_config/generated/server.json"), "utf8"));
const client = JSON.parse(await readFile(path.join(root, "generated/client/data/client.json"), "utf8"));
const serverSchema = await readFile(path.join(root, "src/model/generated/config/schema.ts"), "utf8");
const clientSchema = await readFile(path.join(root, "generated/client/config/schema.ts"), "utf8");
validateGeneratedSpatialData(server);
validateGeneratedActionAndSkillData(server);
const policies = readReloadPolicies(server, client);
const serverParts = partitionData(server, policies), clientParts = partitionData(client, policies);
const json = value => JSON.stringify(value, null, 2) + "\n";
const sha = value => createHash("sha256").update(value.replaceAll("\r\n", "\n")).digest("hex");
const fullFingerprint = sha(`${json(server)}\0${json(client)}`);
const manifest = { formatVersion: 2, schemaFingerprint: sha(serverSchema), clientSchemaFingerprint: sha(clientSchema),
  dataFingerprint: fullFingerprint, hotDataFingerprint: sha(`${json(serverParts.hot)}\0${json(clientParts.hot)}`),
  coldDataFingerprint: sha(`${json(serverParts.cold)}\0${json(clientParts.cold)}`), reloadPolicies: policies };
const output = path.join(root, "generated/config-package");
await mkdir(output, { recursive: true });
for (const [key, file, data] of [["server","server.json",server], ["serverHot","server.hot.json",serverParts.hot],
  ["serverCold","server.cold.json",serverParts.cold], ["client","client.json",client],
  ["clientHot","client.hot.json",clientParts.hot], ["clientCold","client.cold.json",clientParts.cold]]) {
  manifest[`${key}File`] = file; manifest[`${key}Hash`] = sha(json(data));
  await writeFile(path.join(output, file), json(data));
}
await writeFile(path.join(output, "game-config.manifest.json"), json(manifest));
const facade = path.join(root, "generated/client/facade");
await mkdir(facade, { recursive: true });
await writeFile(path.join(facade, "schema.ts"), clientSchema);
await writeFile(path.join(facade, "GameConfigs.ts"), createClientFacade(client, fullFingerprint));
await writeFile(path.join(facade, "index.ts"), '// Generated by config_artifacts.mjs. Do not edit.\nexport * from "./GameConfigs";\nexport * from "./schema";\n');
console.log(`[mmorpg-config] validated data and client facade: ${fullFingerprint.slice(0, 12)}`);
