import { spawnSync } from "node:child_process";
import { cp, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const engine = path.resolve(process.env.TIANGZ_ENGINE_ROOT ?? path.join(root, "../TiangZ"));
const module = path.join(root, "modules/mmorpg");
function run(file, args = []) {
  const result = spawnSync(process.execPath, [file, ...args], { cwd: root, stdio: "inherit", windowsHide: true });
  if (result.error || result.status !== 0) throw result.error ?? new Error(`SDK generation failed: ${file}`);
}
await mkdir(path.join(root, "temp/sdk-server"), { recursive: true });
run(path.join(engine, "tools/codegen_proto.mjs"), ["--module-root", module,
  "--server-output", path.join(root, "temp/sdk-server"), "--typescript-output", path.join(root, "client_sdk/typescript/Generated/Model"),
  "--typescript-runtime-output", path.join(root, "client_sdk/typescript/Core"),
  "--cpp-output", path.join(root, "client_sdk/cpp/include/tiangz/generated"), "--strict-locks"]);
await cp(path.join(engine, "client_sdk/cpp/include/tiangz/client"), path.join(root, "client_sdk/cpp/include/tiangz/client"), { recursive: true });
await cp(path.join(engine, "client_sdk/csharp/Core"), path.join(root, "client_sdk/csharp/Core"), { recursive: true });
await cp(path.join(module, "generated/client/facade"), path.join(root, "client_sdk/typescript/Generated/Config"), { recursive: true });
run(path.join(root, "tools/codegen_csharp_client_sdk.mjs"));
run(path.join(engine, "tools/codegen_godot_client_sdk.mjs"), ["--module-root", module,
  "--schema-lock", path.join(module, "proto/schema.lock.json"), "--opcode-lock", path.join(module, "proto/opcode.lock.json"),
  "--output", path.join(root, "client_sdk/godot/generated/tiangz_proto.gd"), "--class-name", "TiangZProto"]);
const base = path.join(root, "client_sdk/typescript");
const files = [];
async function walk(directory) { for (const entry of await readdir(directory, { withFileTypes: true })) {
  const file = path.join(directory, entry.name); if (entry.isDirectory()) await walk(file); else if (file.endsWith(".ts")) files.push(file);
} }
await walk(path.join(base, "Generated/Model/demo"));
const hash = createHash("sha256");
for (const file of files.sort()) { hash.update(path.relative(base, file).replaceAll(path.sep, "/")); hash.update("\0"); hash.update((await readFile(file, "utf8")).replaceAll("\r\n", "\n")); hash.update("\0"); }
await writeFile(path.join(base, "Generated/ProtocolFingerprint.ts"), `// Generated by tools/codegen_sdk.mjs. Do not edit.\nexport const ProtocolFingerprint = "${hash.digest("hex")}";\n`);
console.log("[example-sdk] composed shared runtime, module protocols and game client helpers");
