import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { collectGeneratedFiles, recordGenerator } from "../../TiangZ/tools/codegen_manifest.mjs";

const scriptFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(scriptFile), "..");
const configFile = path.join(root, "codegen.config.json");
const config = JSON.parse(await readFile(configFile, "utf8"));
const sdk = config.csharpClientSdk;

if (!sdk?.enabled) process.exit(0);
if (typeof sdk.sourceRoot !== "string" || !Array.isArray(sdk.outputRoots)) {
  throw new Error("csharpClientSdk requires sourceRoot and outputRoots");
}

const sourceRoot = path.resolve(root, sdk.sourceRoot);
const outputRoots = sdk.outputRoots.map((item) => path.resolve(root, item));
const schema = JSON.parse(await readFile(path.join(root, "modules/mmorpg/proto/schema.lock.json"), "utf8"));
const opcode = JSON.parse(await readFile(path.join(root, "modules/mmorpg/proto/opcode.lock.json"), "utf8"));
const protocol = parseProtocolAnnotations(await readFile(path.join(root, "modules/mmorpg/proto/OuterMessage_C_10001.proto"), "utf8"));
const allowedFiles = new Set([
  "proto/DataDefine_CS_50001.proto",
  "proto/OuterMessage_C_10001.proto",
]);
const entries = schema.entries
  .filter((entry) => allowedFiles.has(entry.key.split("#", 1)[0]))
  .sort((left, right) => left.name.localeCompare(right.name, "en"));
const entryByName = new Map(entries.map((entry) => [entry.name, entry]));
const codeByName = new Map(
  opcode.entries
    .filter((entry) => allowedFiles.has(entry.key.split("#", 1)[0]))
    .map((entry) => [entry.name, entry.code]),
);
const fingerprint = hashProtocol(entries, codeByName);

await mkdir(path.join(sourceRoot, "Generated", "Demo"), { recursive: true });
await writeFile(
  path.join(sourceRoot, "Generated", "Demo", "Protocol.cs"),
  emitProtocol(entries, codeByName, entryByName, protocol, fingerprint),
  "utf8",
);
for (const outputRoot of outputRoots) {
  await removeGeneratedCSharp(outputRoot);
  for (const file of await discoverCSharp(sourceRoot)) {
    const target = path.join(outputRoot, path.relative(sourceRoot, file));
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, await readFile(file));
  }
}

await recordGenerator(root, {
  id: "csharp-client-sdk",
  command: "npm run codegen:csharp-client-sdk",
  contentInputs: [
    scriptFile,
    configFile,
    path.join(root, "modules/mmorpg/proto/schema.lock.json"),
    path.join(root, "modules/mmorpg/proto/opcode.lock.json"),
    path.join(root, "modules/mmorpg/proto/DataDefine_CS_50001.proto"),
    path.join(root, "modules/mmorpg/proto/OuterMessage_C_10001.proto"),
    ...await discoverCSharp(sourceRoot),
  ],
  outputs: await collectGeneratedFiles(outputRoots.map((item) => ({ path: item, extensions: [".cs"] }))),
  outputRoots: outputRoots.map((item) => ({ path: item, extensions: [".cs"] })),
});

console.log(`[codegen:csharp-client-sdk] generated ${outputRoots.length} SDK copies, fingerprint=${fingerprint.slice(0, 12)}`);

function emitProtocol(entries, codeByName, entryByName, annotations, fingerprint) {
  const messages = entries;
  const outerMessages = entries.filter((entry) => codeByName.has(entry.name));
  const rpcs = outerMessages.filter((entry) => entry.response && entryByName.has(entry.response));
  const clientMessages = outerMessages.filter((entry) => annotations.get(entry.name)?.protocol === "Client");
  const mapMessages = outerMessages.filter((entry) =>
    annotations.get(entry.name)?.protocol === "Map" && !rpcs.some((rpc) => rpc.name === entry.name),
  );
  const lines = [];
  const push = (line = "") => lines.push(line);
  push("// Generated by tools/codegen_csharp_client_sdk.mjs. Do not edit by hand.");
  push("// 由 tools/codegen_csharp_client_sdk.mjs 生成，请勿手工修改。");
  push("#nullable enable");
  push("using System;");
  push("using System.Collections.Generic;");
  push("using System.Threading;");
  push("using System.Threading.Tasks;");
  push("using TiangZ.Client;");
  push("");
  push("namespace TiangZ.Client.Generated.Demo");
  push("{");
  push("");
  push("public static class ProtocolFingerprint");
  push("{");
  push(`    public const string Value = \"${fingerprint}\";`);
  push("}");
  push("");

  push("public static class MsgCode");
  push("{");
  for (const entry of outerMessages.sort((left, right) => left.name.localeCompare(right.name, "en"))) {
    push(`    public const ushort ${entry.name} = ${codeByName.get(entry.name)};`);
  }
  push("}");
  push("");

  for (const entry of messages) emitMessage(entry, push);
  for (const entry of messages) emitCodec(entry, push, entryByName);
  emitDescriptors(push, rpcs, clientMessages, mapMessages, annotations, codeByName, entryByName);
  emitClients(push, rpcs, annotations, mapMessages);
  push("}");
  return `${lines.join("\n")}\n`;
}

function emitMessage(entry, push) {
  const interfaceName = entry.base === "IRequest" || entry.base === "IActorLocationRequest" || entry.base === "IActorRequest"
    ? " : IRpcRequest"
    : entry.base === "IResponse" || entry.base === "IActorLocationResponse" || entry.base === "IActorResponse"
      ? " : IRpcResponse"
      : "";
  push(`public sealed class ${entry.name}${interfaceName}`);
  push("{");
  for (const field of entry.fields) {
    const type = csharpFieldType(field);
    const initializer = field.repeated ? ` = new ${type}();` : "";
    push(`    public ${type} ${pascal(field.name)} { get; set; }${initializer}`);
  }
  push("}");
  push("");
}

function emitCodec(entry, push, entryByName) {
  push(`public static class ${entry.name}Codec`);
  push("{");
  push(`    public static ${entry.name} Decode(byte[] payload)`);
  push("    {");
  push("        var reader = new BinaryReader(payload);");
  push(`        var value = new ${entry.name}();`);
  push("        while (!reader.EndOfMessage)");
  push("        {");
  push("            var tag = reader.ReadTag();");
  push("            switch (tag.FieldNumber)");
  push("            {");
  for (const field of entry.fields) {
    const prop = pascal(field.name);
    const wire = wireType(field.type, field.repeated);
    push(`                case ${field.number} when tag.WireType == ${wire}:`);
    if (field.repeated) {
      push(`                    value.${prop}.Add(${readExpression(field.type)});`);
    } else {
      push(`                    value.${prop} = ${readExpression(field.type)};`);
    }
    push("                    break;");
  }
  push("                default:");
  push("                    reader.Skip(tag.WireType);");
  push("                    break;");
  push("            }");
  push("        }");
  push("        return value;");
  push("    }");
  push("");
  push(`    public static byte[] Encode(${entry.name} value)`);
  push("    {");
  push("        var writer = new BinaryWriter();");
  for (const field of entry.fields) {
    const prop = `value.${pascal(field.name)}`;
    if (field.repeated) {
      push(`        foreach (var item in ${prop})`);
      push("        {");
      push(`            ${writeStatement(field, "item")}`);
      push("        }");
    } else {
      push(`        ${writeStatement(field, prop)}`);
    }
  }
  push("        return writer.ToArray();");
  push("    }");
  push("}");
  push("");
}

function emitDescriptors(push, rpcs, clientMessages, mapMessages, annotations, codeByName, entryByName) {
  const groups = new Map();
  for (const rpc of rpcs) {
    const item = annotations.get(rpc.name) ?? {};
    const group = item.protocol ?? "Client";
    const list = groups.get(group) ?? [];
    list.push(rpc);
    groups.set(group, list);
  }
  for (const [group, items] of groups) {
    push(`public static class ${group}Protocol`);
    push("{");
    for (const request of items) {
      const response = entryByName.get(request.response);
      const method = annotations.get(request.name)?.method ?? rpcMethod(request.name);
      const name = `${group}.${method}`;
      push(`    public static readonly RpcDescriptor<${request.name}, ${response.name}> ${method} = new(`);
      push(`        \"${name}\", MsgCode.${request.name}, MsgCode.${response.name},`);
      push(`        ${request.name}Codec.Encode, ${response.name}Codec.Decode,`);
      push(`        static (request, rpcId) => request.RpcId = rpcId,`);
      push(`        static response => response.RpcId, static response => response.Error, static response => response.Message);`);
    }
    push("}");
    push("");
  }

  push("public static class ClientMessages");
  push("{");
  for (const message of clientMessages) {
    const method = annotations.get(message.name)?.method ?? rpcMethod(message.name);
    push(`    public static readonly MessageDescriptor<${message.name}> ${method} = new(`);
    push(`        \"Client.${method}\", MsgCode.${message.name}, ${message.name}Codec.Encode, ${message.name}Codec.Decode);`);
  }
  push("}");
  push("");

  push("public static class MapMessages");
  push("{");
  for (const message of mapMessages) {
    const method = annotations.get(message.name)?.method ?? rpcMethod(message.name);
    push(`    public static readonly MessageDescriptor<${message.name}> ${method} = new(`);
    push(`        \"Map.${method}\", MsgCode.${message.name}, ${message.name}Codec.Encode, ${message.name}Codec.Decode);`);
  }
  push("}");
  push("");
}

function emitClients(push, rpcs, annotations, mapMessages) {
  const groups = new Map();
  for (const rpc of rpcs) {
    const group = annotations.get(rpc.name)?.protocol ?? "Client";
    const list = groups.get(group) ?? [];
    list.push(rpc);
    groups.set(group, list);
  }
  for (const [group, items] of groups) {
    push(`public sealed class ${group}Client`);
    push("{");
    push("    private readonly RpcSocket socket;");
    push("    public " + group + "Client(RpcSocket socket) => this.socket = socket;");
    push("");
    for (const request of items) {
      const method = annotations.get(request.name)?.method ?? rpcMethod(request.name);
      const response = request.response;
      push(`    public Task<${response}> ${method}Async(${request.name} request, CancellationToken cancellationToken = default) =>`);
      push(`        socket.CallAsync(${group}Protocol.${method}, request, cancellationToken);`);
    }
    if (group === "Map") {
      for (const message of mapMessages.filter((entry) => entry.name === "C2M_Move")) {
        const method = annotations.get(message.name)?.method ?? rpcMethod(message.name);
        push(`    public Task ${method}Async(${message.name} message, CancellationToken cancellationToken = default) =>`);
        push(`        socket.SendAsync(MapMessages.${method}, message, cancellationToken);`);
      }
    }
    push("}");
    push("");
  }
  if (mapMessages.some((entry) => entry.name === "C2M_Move")) {
    push("// C2M_Move is a one-way actor message, not an RPC.");
    push("// C2M_Move 是单向 Actor 消息，不是 RPC。");
  }
}

function readExpression(type) {
  switch (type) {
    case "string": return "reader.ReadString()";
    case "bytes": return "reader.ReadBytes()";
    case "uint32": return "reader.ReadUInt32()";
    case "int32": return "reader.ReadInt32()";
    case "sint32": return "reader.ReadSInt32()";
    case "uint64": return "reader.ReadUInt64()";
    case "int64": return "reader.ReadInt64()";
    case "bool": return "reader.ReadBool()";
    case "float": return "reader.ReadFloat()";
    case "double": return "reader.ReadDouble()";
    default: return `${type}Codec.Decode(reader.ReadBytes())`;
  }
}

function writeStatement(field, expression) {
  const number = field.number;
  const type = field.type;
  const check = field.repeated ? "true" : defaultCheck(type, expression);
  if (field.repeated) {
    switch (type) {
      case "string": return `writer.WriteString(${number}, ${expression}, true);`;
      case "bytes": return `writer.WriteBytes(${number}, ${expression}, true);`;
      case "uint32": return `writer.WriteUInt32(${number}, ${expression}, true);`;
      case "int32": return `writer.WriteInt32(${number}, ${expression}, true);`;
      case "sint32": return `writer.WriteSInt32(${number}, ${expression}, true);`;
      case "uint64": return `writer.WriteUInt64(${number}, ${expression}, true);`;
      case "int64": return `writer.WriteInt64(${number}, ${expression}, true);`;
      case "bool": return `writer.WriteBool(${number}, ${expression}, true);`;
      case "float": return `writer.WriteFloat(${number}, ${expression}, true);`;
      case "double": return `writer.WriteDouble(${number}, ${expression}, true);`;
      default: return `writer.WriteMessage(${number}, ${expression} == null ? null : ${type}Codec.Encode(${expression}));`;
    }
  }
  switch (type) {
    case "string": return `if (${check}) writer.WriteString(${number}, ${expression});`;
    case "bytes": return `if (${check}) writer.WriteBytes(${number}, ${expression});`;
    case "uint32": return `if (${check}) writer.WriteUInt32(${number}, ${expression});`;
    case "int32": return `if (${check}) writer.WriteInt32(${number}, ${expression});`;
    case "sint32": return `if (${check}) writer.WriteSInt32(${number}, ${expression});`;
    case "uint64": return `if (${check}) writer.WriteUInt64(${number}, ${expression});`;
    case "int64": return `if (${check}) writer.WriteInt64(${number}, ${expression});`;
    case "bool": return `if (${check}) writer.WriteBool(${number}, ${expression});`;
    case "float": return `if (${check}) writer.WriteFloat(${number}, ${expression});`;
    case "double": return `if (${check}) writer.WriteDouble(${number}, ${expression});`;
    default: return `if (${check}) writer.WriteMessage(${number}, ${type}Codec.Encode(${expression}));`;
  }
}

function defaultCheck(type, expression) {
  if (type === "string") return `!string.IsNullOrEmpty(${expression})`;
  if (type === "bytes") return `${expression} != null && ${expression}.Length > 0`;
  if (["bool"].includes(type)) return expression;
  if (["float", "double"].includes(type)) return `${expression} != 0`;
  if (["uint32", "int32", "sint32", "uint64", "int64"].includes(type)) return `${expression} != 0`;
  return `${expression} != null`;
}

function csharpFieldType(field) {
  const scalar = {
    string: "string",
    bytes: "byte[]",
    uint32: "uint",
    int32: "int",
    sint32: "int",
    uint64: "ulong",
    int64: "long",
    bool: "bool",
    float: "float",
    double: "double",
  }[field.type] ?? field.type;
  if (field.repeated) return `List<${scalar}>`;
  const referenceType = field.type === "string" || field.type === "bytes" || !["uint32", "int32", "sint32", "uint64", "int64", "bool", "float", "double"].includes(field.type);
  return referenceType ? `${scalar}?` : scalar;
}

function wireType(type) {
  if (["string", "bytes"].includes(type) || !["uint32", "int32", "sint32", "uint64", "int64", "bool", "float", "double"].includes(type)) return 2;
  if (["float"].includes(type)) return 5;
  if (["double"].includes(type)) return 1;
  return 0;
}

function parseProtocolAnnotations(text) {
  const result = new Map();
  const lines = text.split(/\r?\n/);
  let pending = [];
  for (const line of lines) {
    const message = line.match(/^\s*message\s+(\w+)/);
    if (message) {
      const comments = [...pending, line];
      const protocol = comments.join("\n").match(/@ets\.msg\s+protocol=([A-Za-z0-9_]+)/)?.[1];
      const method = comments.join("\n").match(/@ets\.msg\s+protocol=[A-Za-z0-9_]+\s+method=([A-Za-z0-9_]+)/)?.[1];
      result.set(message[1], { protocol, method });
      pending = [];
      continue;
    }
    if (/^\s*\/\//.test(line)) pending.push(line);
    else if (line.trim() !== "") pending = [];
  }
  return result;
}

function rpcMethod(name) {
  const suffix = name.replace(/^(C2S_|S2C_|C2G_|G2C_|C2M_|M2C_)/, "");
  return suffix.startsWith("Map") && suffix !== "Map" ? suffix.slice(3) : suffix;
}

function pascal(name) {
  return name.split("_").filter(Boolean).map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

function hashProtocol(entries, codeByName) {
  const hash = createHash("sha256");
  for (const entry of entries) {
    hash.update(JSON.stringify(entry));
    hash.update(String(codeByName.get(entry.name) ?? ""));
  }
  return hash.digest("hex");
}

async function discoverCSharp(directory) {
  const files = [];
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (error?.code === "ENOENT") return files;
    throw error;
  }
  for (const entry of entries) {
    if (entry.isDirectory() && (entry.name === "bin" || entry.name === "obj")) continue;
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await discoverCSharp(fullPath));
    else if (entry.isFile() && entry.name.endsWith(".cs")) files.push(fullPath);
  }
  return files.sort((left, right) => left.localeCompare(right, "en"));
}

async function removeGeneratedCSharp(directory) {
  for (const file of await discoverCSharp(directory)) await rm(file, { force: true });
}
